import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { estimateDownloads } from "@/lib/aso/downloads";

// Parity vectors generated by scripts/gen-aso-parity-vectors.py, which runs
// respectaso's real Python DownloadEstimator.estimate() on synthetic
// fixtures. Python's round() is banker's rounding (half-to-even); the TS
// port uses Math.round(x*100)/100, so numeric fields are compared with a
// tolerance covering the maximum possible discrepancy between the two
// rounding modes at 2 decimals (0.005 half-tick + slack).

interface DownloadPositionVector {
  pos: number;
  ttr: number;
  downloads_low: number;
  downloads_high: number;
}

interface DownloadCaseVector {
  popularity: number | null;
  country: string;
  expected: {
    daily_searches: number;
    positions: DownloadPositionVector[];
    tiers: {
      top_5: { low: number; high: number };
      top_6_10: { low: number; high: number };
      top_11_20: { low: number; high: number };
    };
  };
}

const vectors = JSON.parse(
  readFileSync(new URL("./parity-vectors.json", import.meta.url), "utf8"),
) as { download_cases: DownloadCaseVector[] };

const TOLERANCE = 0.011;

function expectClose(actual: number, expected: number, label: string): void {
  expect(Math.abs(actual - expected), `${label}: ${actual} vs ${expected}`).toBeLessThanOrEqual(
    TOLERANCE,
  );
}

describe("estimateDownloads parity with respectaso Python DownloadEstimator", () => {
  vectors.download_cases.forEach((c, idx) => {
    it(`case ${idx}: popularity=${String(c.popularity)} country=${c.country}`, () => {
      const result = estimateDownloads(c.popularity, c.country);

      expectClose(result.dailySearches, c.expected.daily_searches, "dailySearches");
      expect(result.positions).toHaveLength(c.expected.positions.length);

      c.expected.positions.forEach((expectedPos, i) => {
        const actualPos = result.positions[i];
        expect(actualPos.pos).toBe(expectedPos.pos);
        expectClose(actualPos.ttr, expectedPos.ttr, `pos ${expectedPos.pos} ttr`);
        expectClose(
          actualPos.downloadsLow,
          expectedPos.downloads_low,
          `pos ${expectedPos.pos} downloadsLow`,
        );
        expectClose(
          actualPos.downloadsHigh,
          expectedPos.downloads_high,
          `pos ${expectedPos.pos} downloadsHigh`,
        );
      });

      expectClose(result.tiers.top5.low, c.expected.tiers.top_5.low, "top5.low");
      expectClose(result.tiers.top5.high, c.expected.tiers.top_5.high, "top5.high");
      expectClose(result.tiers.top6To10.low, c.expected.tiers.top_6_10.low, "top6To10.low");
      expectClose(result.tiers.top6To10.high, c.expected.tiers.top_6_10.high, "top6To10.high");
      expectClose(result.tiers.top11To20.low, c.expected.tiers.top_11_20.low, "top11To20.low");
      expectClose(
        result.tiers.top11To20.high,
        c.expected.tiers.top_11_20.high,
        "top11To20.high",
      );
    });
  });
});

describe("estimateDownloads – unit behaviour", () => {
  it("returns all zeros when popularity is null", () => {
    const result = estimateDownloads(null);
    expect(result.dailySearches).toBe(0);
    expect(result.positions.every((p) => p.downloadsLow === 0 && p.downloadsHigh === 0)).toBe(
      true,
    );
    expect(result.tiers).toEqual({
      top5: { low: 0, high: 0 },
      top6To10: { low: 0, high: 0 },
      top11To20: { low: 0, high: 0 },
    });
  });

  it("falls back to the default 0.03 market factor for an unknown country", () => {
    const unknown = estimateDownloads(50, "zz");
    const us = estimateDownloads(50, "us");
    expect(unknown.dailySearches).toBeCloseTo(us.dailySearches * 0.03, 2);
  });

  it("scales linearly below the first popularity anchor (pop 5 → 1 search/day)", () => {
    const result = estimateDownloads(2.5);
    expect(result.dailySearches).toBeCloseTo(0.5, 2); // 1 * (2.5 / 5)
  });

  it("treats an empty-string country as the default 'us' market", () => {
    const empty = estimateDownloads(50, "");
    const us = estimateDownloads(50, "us");
    expect(empty.dailySearches).toBe(us.dailySearches);
  });

  it("defaults to the 'us' market when country is omitted", () => {
    expect(estimateDownloads(50)).toEqual(estimateDownloads(50, "us"));
  });
});
