import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { calcOpportunity, classifyKeyword } from "@/lib/aso/scoring";
import {
  estimatePopularity,
  calculateDifficulty,
  type CompetitorApp,
} from "@/lib/aso/estimators";

// Parity vectors generated by scripts/gen-aso-parity-vectors.py, which runs
// respectaso's real Python scoring code on synthetic fixtures with a frozen
// clock. The TS port must reproduce every value.

interface ParityCase {
  name: string;
  keyword: string;
  competitors: CompetitorApp[];
  expected_popularity: number | null;
  expected_difficulty: Record<string, number | string | boolean | null>;
  expected_opportunity: number;
  expected_classification: string;
}

const vectors = JSON.parse(
  readFileSync(new URL("./parity-vectors.json", import.meta.url), "utf8"),
) as { frozen_now: string; cases: ParityCase[] };

const now = new Date(vectors.frozen_now);

// Sub-scores are stored rounded to 1 decimal by Python (banker's rounding);
// allow just over half a tick for the rounding-mode difference.
const SUB_SCORES = new Set([
  "rating_volume",
  "review_velocity",
  "dominant_players",
  "rating_quality",
  "market_age",
  "publisher_diversity",
  "title_relevance",
]);

const toCamel = (s: string) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());

describe("parity with respectaso Python scoring", () => {
  for (const c of vectors.cases) {
    it(c.name, () => {
      const popularity = estimatePopularity(c.competitors, c.keyword);
      expect(popularity).toBe(c.expected_popularity);

      const { total, breakdown } = calculateDifficulty(c.competitors, c.keyword, now);
      const record = breakdown as unknown as Record<string, number | string | boolean | null>;
      for (const [key, expected] of Object.entries(c.expected_difficulty)) {
        const actual = record[toCamel(key)];
        if (SUB_SCORES.has(key) && typeof expected === "number") {
          expect(
            Math.abs((actual as number) - expected),
            `${key}: ${actual} vs ${expected}`,
          ).toBeLessThanOrEqual(0.06);
        } else {
          expect(actual, key).toBe(expected);
        }
      }
      expect(total).toBe(c.expected_difficulty.total_score);

      expect(calcOpportunity(popularity ?? 0, total)).toBe(c.expected_opportunity);
      expect(classifyKeyword(popularity ?? 0, total)).toBe(c.expected_classification);
    });
  }
});
