import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { calculateDifficulty, type CompetitorApp, type RankingTier } from "@/lib/aso/estimators";

// Parity vectors generated by scripts/gen-aso-parity-vectors.py, which runs
// respectaso's real Python _compute_ranking_tiers on synthetic fixtures with
// a frozen clock. The TS port must reproduce every field except `highlights`
// (English prose bullets – intentionally not ported, see estimators.ts).

interface ExpectedTier {
  min_reviews: number;
  weakest_app: string;
  median_reviews: number;
  weak_count: number;
  fresh_count: number;
  title_keyword_count: number;
  total_apps: number;
  tier_score: number;
  label: string;
}

interface ParityCase {
  name: string;
  keyword: string;
  competitors: CompetitorApp[];
  expected_ranking_tiers?: {
    top_5: ExpectedTier;
    top_10: ExpectedTier;
    top_20: ExpectedTier;
  };
}

const vectors = JSON.parse(
  readFileSync(new URL("./parity-vectors.json", import.meta.url), "utf8"),
) as { frozen_now: string; cases: ParityCase[] };

const frozenNow = new Date(vectors.frozen_now);

function expectTier(actual: RankingTier, expected: ExpectedTier) {
  expect(actual.minReviews).toBe(expected.min_reviews);
  expect(actual.weakestApp).toBe(expected.weakest_app);
  expect(actual.medianReviews).toBe(expected.median_reviews);
  expect(actual.weakCount).toBe(expected.weak_count);
  expect(actual.freshCount).toBe(expected.fresh_count);
  expect(actual.titleKeywordCount).toBe(expected.title_keyword_count);
  expect(actual.totalApps).toBe(expected.total_apps);
  expect(actual.tierScore).toBe(expected.tier_score);
  expect(actual.label).toBe(expected.label);
}

describe("ranking tiers parity with respectaso Python _compute_ranking_tiers", () => {
  for (const c of vectors.cases) {
    if (!c.expected_ranking_tiers) continue;

    it(c.name, () => {
      const { breakdown } = calculateDifficulty(c.competitors, c.keyword, frozenNow);
      expectTier(breakdown.rankingTiers.top5, c.expected_ranking_tiers!.top_5);
      expectTier(breakdown.rankingTiers.top10, c.expected_ranking_tiers!.top_10);
      expectTier(breakdown.rankingTiers.top20, c.expected_ranking_tiers!.top_20);
    });
  }
});

describe("ranking tiers – empty competitors branch", () => {
  it("returns the wide-open default for all three tiers (n==0 branch of the Python port)", () => {
    const { breakdown } = calculateDifficulty([], "anything");
    const empty: Omit<RankingTier, never> = {
      minReviews: 0,
      weakestApp: "",
      medianReviews: 0,
      weakCount: 0,
      freshCount: 0,
      titleKeywordCount: 0,
      totalApps: 0,
      tierScore: 0,
      label: "Easy",
    };
    expect(breakdown.rankingTiers.top5).toEqual(empty);
    expect(breakdown.rankingTiers.top10).toEqual(empty);
    expect(breakdown.rankingTiers.top20).toEqual(empty);
  });
});
