/* Portions derived from appscreen (https://github.com/YUZU-Hub/appscreen), MIT License, Copyright YuzuHub */
// EMOJI_DATA ported verbatim from lucide-icons.js:3-294 (8 categories, 273 entries).
export interface EmojiEntry { emoji: string; name: string; keywords: string[] }

export const EMOJI_CATEGORIES: { key: string; entries: EmojiEntry[] }[] = [
  { key: "popular", entries: [
    { emoji: "⭐", name: "Star", keywords: ["star", "favorite", "rating"] },
    { emoji: "🔥", name: "Fire", keywords: ["fire", "hot", "trending"] },
    { emoji: "❤️", name: "Red Heart", keywords: ["heart", "love", "like"] },
    { emoji: "✨", name: "Sparkles", keywords: ["sparkles", "magic", "new"] },
    { emoji: "🎉", name: "Party Popper", keywords: ["party", "celebrate", "confetti"] },
    { emoji: "🚀", name: "Rocket", keywords: ["rocket", "launch", "fast", "speed"] },
    { emoji: "💡", name: "Light Bulb", keywords: ["idea", "bulb", "light", "tip"] },
    { emoji: "✅", name: "Check Mark", keywords: ["check", "done", "complete", "yes"] },
    { emoji: "🎯", name: "Bullseye", keywords: ["target", "goal", "aim", "bullseye"] },
    { emoji: "💪", name: "Flexed Bicep", keywords: ["strong", "muscle", "power", "flex"] },
    { emoji: "👑", name: "Crown", keywords: ["crown", "king", "queen", "royal", "best"] },
    { emoji: "🏆", name: "Trophy", keywords: ["trophy", "winner", "award", "champion"] },
    { emoji: "💰", name: "Money Bag", keywords: ["money", "rich", "dollar", "finance"] },
    { emoji: "🎨", name: "Artist Palette", keywords: ["art", "paint", "design", "creative"] },
    { emoji: "📱", name: "Mobile Phone", keywords: ["phone", "mobile", "smartphone", "app"] },
    { emoji: "💻", name: "Laptop", keywords: ["laptop", "computer", "work", "code"] },
    { emoji: "🔒", name: "Lock", keywords: ["lock", "secure", "private", "safe"] },
    { emoji: "⚡", name: "Lightning", keywords: ["lightning", "fast", "electric", "power", "zap"] },
    { emoji: "🌟", name: "Glowing Star", keywords: ["star", "glow", "bright", "shine"] },
    { emoji: "💎", name: "Gem", keywords: ["gem", "diamond", "premium", "jewel"] },
    { emoji: "🔔", name: "Bell", keywords: ["bell", "notification", "alert", "ring"] },
    { emoji: "📊", name: "Bar Chart", keywords: ["chart", "graph", "stats", "analytics"] },
    { emoji: "🎵", name: "Musical Note", keywords: ["music", "note", "song", "audio"] },
    { emoji: "📸", name: "Camera Flash", keywords: ["camera", "photo", "picture", "snap"] },
    { emoji: "🌈", name: "Rainbow", keywords: ["rainbow", "color", "pride", "beautiful"] },
    { emoji: "💬", name: "Speech Bubble", keywords: ["speech", "chat", "message", "talk"] },
    { emoji: "🛡️", name: "Shield", keywords: ["shield", "protect", "defense", "safe"] },
    { emoji: "🎁", name: "Gift", keywords: ["gift", "present", "surprise", "reward"] },
    { emoji: "🔑", name: "Key", keywords: ["key", "unlock", "access", "password"] },
    { emoji: "📈", name: "Chart Up", keywords: ["growth", "increase", "trending", "up"] },
    { emoji: "❌", name: "Cross Mark", keywords: ["cross", "no", "wrong", "delete", "cancel"] },
    { emoji: "💯", name: "Hundred", keywords: ["hundred", "perfect", "score", "100"] },
  ] },
  { key: "smileys", entries: [
    { emoji: "😀", name: "Grinning", keywords: ["happy", "smile", "grin"] },
    { emoji: "😃", name: "Smiley", keywords: ["happy", "smile", "joy"] },
    { emoji: "😄", name: "Smile", keywords: ["happy", "smile", "glad"] },
    { emoji: "😁", name: "Beaming", keywords: ["grin", "happy", "teeth"] },
    { emoji: "😆", name: "Laughing", keywords: ["laugh", "lol", "happy"] },
    { emoji: "😅", name: "Sweat Smile", keywords: ["sweat", "nervous", "relief"] },
    { emoji: "🤣", name: "ROFL", keywords: ["rolling", "laugh", "lol"] },
    { emoji: "😂", name: "Joy", keywords: ["tears", "laugh", "funny"] },
    { emoji: "🙂", name: "Slight Smile", keywords: ["smile", "okay", "fine"] },
    { emoji: "😉", name: "Wink", keywords: ["wink", "flirt", "playful"] },
    { emoji: "😊", name: "Blush", keywords: ["blush", "happy", "warm"] },
    { emoji: "😇", name: "Halo", keywords: ["angel", "innocent", "good"] },
    { emoji: "🥰", name: "Love Face", keywords: ["love", "hearts", "adore"] },
    { emoji: "😍", name: "Heart Eyes", keywords: ["love", "heart", "wow"] },
    { emoji: "🤩", name: "Star Struck", keywords: ["stars", "amazing", "wow"] },
    { emoji: "😘", name: "Kissing", keywords: ["kiss", "love", "muah"] },
    { emoji: "😎", name: "Cool", keywords: ["cool", "sunglasses", "confident"] },
    { emoji: "🤔", name: "Thinking", keywords: ["think", "hmm", "consider"] },
    { emoji: "🤗", name: "Hugging", keywords: ["hug", "warm", "embrace"] },
    { emoji: "🤯", name: "Mind Blown", keywords: ["mind", "blown", "explode", "shocked"] },
    { emoji: "😱", name: "Screaming", keywords: ["scream", "shock", "fear"] },
    { emoji: "🥳", name: "Partying", keywords: ["party", "celebrate", "fun"] },
    { emoji: "😴", name: "Sleeping", keywords: ["sleep", "zzz", "tired"] },
    { emoji: "🤫", name: "Shushing", keywords: ["quiet", "secret", "shh"] },
    { emoji: "🫡", name: "Saluting", keywords: ["salute", "respect", "sir"] },
    { emoji: "🤓", name: "Nerd", keywords: ["nerd", "smart", "glasses"] },
    { emoji: "😈", name: "Devil", keywords: ["devil", "evil", "imp", "mischief"] },
    { emoji: "👻", name: "Ghost", keywords: ["ghost", "boo", "spooky"] },
    { emoji: "🤖", name: "Robot", keywords: ["robot", "ai", "machine"] },
    { emoji: "👽", name: "Alien", keywords: ["alien", "ufo", "space"] },
  ] },
  { key: "objects", entries: [
    { emoji: "⌚", name: "Watch", keywords: ["watch", "time", "wrist"] },
    { emoji: "📱", name: "Phone", keywords: ["phone", "mobile", "cell"] },
    { emoji: "💻", name: "Laptop", keywords: ["laptop", "computer"] },
    { emoji: "⌨️", name: "Keyboard", keywords: ["keyboard", "type", "input"] },
    { emoji: "🖥️", name: "Desktop", keywords: ["desktop", "monitor", "screen"] },
    { emoji: "🖨️", name: "Printer", keywords: ["printer", "print"] },
    { emoji: "🖱️", name: "Mouse", keywords: ["mouse", "click", "cursor"] },
    { emoji: "💿", name: "CD", keywords: ["cd", "disc", "dvd"] },
    { emoji: "📷", name: "Camera", keywords: ["camera", "photo"] },
    { emoji: "🎥", name: "Movie Camera", keywords: ["movie", "film", "video"] },
    { emoji: "📺", name: "Television", keywords: ["tv", "television", "screen"] },
    { emoji: "📻", name: "Radio", keywords: ["radio", "audio", "broadcast"] },
    { emoji: "🎙️", name: "Microphone", keywords: ["microphone", "podcast", "record"] },
    { emoji: "🎧", name: "Headphones", keywords: ["headphones", "music", "audio"] },
    { emoji: "🔋", name: "Battery", keywords: ["battery", "power", "charge"] },
    { emoji: "🔌", name: "Plug", keywords: ["plug", "power", "electric"] },
    { emoji: "💡", name: "Bulb", keywords: ["bulb", "idea", "light"] },
    { emoji: "🔦", name: "Flashlight", keywords: ["flashlight", "torch", "light"] },
    { emoji: "📦", name: "Package", keywords: ["package", "box", "ship", "delivery"] },
    { emoji: "✉️", name: "Envelope", keywords: ["envelope", "mail", "email", "letter"] },
    { emoji: "📋", name: "Clipboard", keywords: ["clipboard", "list", "paste"] },
    { emoji: "📝", name: "Memo", keywords: ["memo", "note", "write"] },
    { emoji: "📁", name: "Folder", keywords: ["folder", "file", "directory"] },
    { emoji: "📅", name: "Calendar", keywords: ["calendar", "date", "schedule"] },
    { emoji: "📌", name: "Pushpin", keywords: ["pin", "pushpin", "location"] },
    { emoji: "📎", name: "Paperclip", keywords: ["paperclip", "attach", "clip"] },
    { emoji: "✂️", name: "Scissors", keywords: ["scissors", "cut", "trim"] },
    { emoji: "🔧", name: "Wrench", keywords: ["wrench", "tool", "fix", "settings"] },
    { emoji: "🔨", name: "Hammer", keywords: ["hammer", "tool", "build"] },
    { emoji: "⚙️", name: "Gear", keywords: ["gear", "settings", "cog", "config"] },
    { emoji: "🧲", name: "Magnet", keywords: ["magnet", "attract"] },
    { emoji: "🧪", name: "Test Tube", keywords: ["test", "lab", "science", "experiment"] },
    { emoji: "💊", name: "Pill", keywords: ["pill", "medicine", "health"] },
    { emoji: "🪙", name: "Coin", keywords: ["coin", "money", "gold"] },
    { emoji: "💳", name: "Credit Card", keywords: ["credit", "card", "payment", "bank"] },
    { emoji: "🛒", name: "Shopping Cart", keywords: ["cart", "shopping", "buy"] },
    { emoji: "🎮", name: "Game Controller", keywords: ["game", "controller", "play", "gaming"] },
    { emoji: "🕹️", name: "Joystick", keywords: ["joystick", "game", "arcade"] },
    { emoji: "🧩", name: "Puzzle", keywords: ["puzzle", "piece", "jigsaw"] },
  ] },
  { key: "symbols", entries: [
    { emoji: "❤️", name: "Red Heart", keywords: ["heart", "love", "red"] },
    { emoji: "🧡", name: "Orange Heart", keywords: ["heart", "orange"] },
    { emoji: "💛", name: "Yellow Heart", keywords: ["heart", "yellow"] },
    { emoji: "💚", name: "Green Heart", keywords: ["heart", "green"] },
    { emoji: "💙", name: "Blue Heart", keywords: ["heart", "blue"] },
    { emoji: "💜", name: "Purple Heart", keywords: ["heart", "purple"] },
    { emoji: "🖤", name: "Black Heart", keywords: ["heart", "black"] },
    { emoji: "🤍", name: "White Heart", keywords: ["heart", "white"] },
    { emoji: "💔", name: "Broken Heart", keywords: ["heart", "broken", "sad"] },
    { emoji: "♻️", name: "Recycle", keywords: ["recycle", "green", "eco"] },
    { emoji: "⚠️", name: "Warning", keywords: ["warning", "alert", "caution"] },
    { emoji: "🚫", name: "Prohibited", keywords: ["no", "prohibited", "ban", "forbidden"] },
    { emoji: "✅", name: "Check", keywords: ["check", "done", "complete", "approved"] },
    { emoji: "❌", name: "Cross", keywords: ["cross", "no", "wrong", "cancel"] },
    { emoji: "❓", name: "Question", keywords: ["question", "ask", "help"] },
    { emoji: "❗", name: "Exclamation", keywords: ["exclamation", "alert", "important"] },
    { emoji: "💲", name: "Dollar", keywords: ["dollar", "money", "price"] },
    { emoji: "🔴", name: "Red Circle", keywords: ["red", "circle", "dot"] },
    { emoji: "🟢", name: "Green Circle", keywords: ["green", "circle", "dot", "online"] },
    { emoji: "🔵", name: "Blue Circle", keywords: ["blue", "circle", "dot"] },
    { emoji: "🟡", name: "Yellow Circle", keywords: ["yellow", "circle", "dot"] },
    { emoji: "🟠", name: "Orange Circle", keywords: ["orange", "circle", "dot"] },
    { emoji: "🟣", name: "Purple Circle", keywords: ["purple", "circle", "dot"] },
    { emoji: "⬛", name: "Black Square", keywords: ["black", "square"] },
    { emoji: "⬜", name: "White Square", keywords: ["white", "square"] },
    { emoji: "🔶", name: "Orange Diamond", keywords: ["orange", "diamond"] },
    { emoji: "🔷", name: "Blue Diamond", keywords: ["blue", "diamond"] },
    { emoji: "▶️", name: "Play", keywords: ["play", "start", "video"] },
    { emoji: "⏸️", name: "Pause", keywords: ["pause", "stop"] },
    { emoji: "⏩", name: "Fast Forward", keywords: ["forward", "fast", "skip"] },
    { emoji: "🔀", name: "Shuffle", keywords: ["shuffle", "random", "mix"] },
    { emoji: "🔁", name: "Repeat", keywords: ["repeat", "loop", "cycle"] },
    { emoji: "➕", name: "Plus", keywords: ["plus", "add", "new"] },
    { emoji: "➖", name: "Minus", keywords: ["minus", "subtract", "remove"] },
    { emoji: "➡️", name: "Right Arrow", keywords: ["arrow", "right", "next", "forward"] },
    { emoji: "⬅️", name: "Left Arrow", keywords: ["arrow", "left", "back"] },
    { emoji: "⬆️", name: "Up Arrow", keywords: ["arrow", "up"] },
    { emoji: "⬇️", name: "Down Arrow", keywords: ["arrow", "down"] },
    { emoji: "↗️", name: "Up-Right Arrow", keywords: ["arrow", "diagonal", "growth"] },
    { emoji: "🔗", name: "Link", keywords: ["link", "chain", "url"] },
    { emoji: "♾️", name: "Infinity", keywords: ["infinity", "forever", "loop"] },
    { emoji: "©️", name: "Copyright", keywords: ["copyright", "legal"] },
    { emoji: "™️", name: "Trademark", keywords: ["trademark", "brand"] },
    { emoji: "®️", name: "Registered", keywords: ["registered", "brand"] },
  ] },
  { key: "animals", entries: [
    { emoji: "🐶", name: "Dog", keywords: ["dog", "puppy", "pet"] },
    { emoji: "🐱", name: "Cat", keywords: ["cat", "kitten", "pet"] },
    { emoji: "🐭", name: "Mouse", keywords: ["mouse", "rodent"] },
    { emoji: "🐹", name: "Hamster", keywords: ["hamster", "pet"] },
    { emoji: "🐰", name: "Rabbit", keywords: ["rabbit", "bunny"] },
    { emoji: "🦊", name: "Fox", keywords: ["fox", "clever"] },
    { emoji: "🐻", name: "Bear", keywords: ["bear", "teddy"] },
    { emoji: "🐼", name: "Panda", keywords: ["panda", "bamboo"] },
    { emoji: "🐨", name: "Koala", keywords: ["koala", "australia"] },
    { emoji: "🦁", name: "Lion", keywords: ["lion", "king", "brave"] },
    { emoji: "🐯", name: "Tiger", keywords: ["tiger", "fierce"] },
    { emoji: "🐮", name: "Cow", keywords: ["cow", "milk", "farm"] },
    { emoji: "🐷", name: "Pig", keywords: ["pig", "oink", "farm"] },
    { emoji: "🐸", name: "Frog", keywords: ["frog", "toad"] },
    { emoji: "🐵", name: "Monkey", keywords: ["monkey", "ape"] },
    { emoji: "🐔", name: "Chicken", keywords: ["chicken", "hen", "farm"] },
    { emoji: "🐧", name: "Penguin", keywords: ["penguin", "cold", "ice"] },
    { emoji: "🐦", name: "Bird", keywords: ["bird", "tweet", "fly"] },
    { emoji: "🦅", name: "Eagle", keywords: ["eagle", "bird", "fly"] },
    { emoji: "🦋", name: "Butterfly", keywords: ["butterfly", "insect", "beautiful"] },
    { emoji: "🐛", name: "Bug", keywords: ["bug", "insect", "caterpillar"] },
    { emoji: "🐝", name: "Bee", keywords: ["bee", "honey", "buzz"] },
    { emoji: "🐠", name: "Fish", keywords: ["fish", "tropical", "sea"] },
    { emoji: "🐬", name: "Dolphin", keywords: ["dolphin", "sea", "smart"] },
    { emoji: "🦄", name: "Unicorn", keywords: ["unicorn", "magic", "fantasy"] },
    { emoji: "🐉", name: "Dragon", keywords: ["dragon", "fire", "fantasy"] },
    { emoji: "🦈", name: "Shark", keywords: ["shark", "sea", "danger"] },
    { emoji: "🐙", name: "Octopus", keywords: ["octopus", "sea", "tentacles"] },
    { emoji: "🦉", name: "Owl", keywords: ["owl", "wise", "night"] },
    { emoji: "🐺", name: "Wolf", keywords: ["wolf", "wild", "howl"] },
  ] },
  { key: "food", entries: [
    { emoji: "🍎", name: "Apple", keywords: ["apple", "fruit", "red"] },
    { emoji: "🍊", name: "Orange", keywords: ["orange", "fruit", "citrus"] },
    { emoji: "🍋", name: "Lemon", keywords: ["lemon", "fruit", "citrus", "sour"] },
    { emoji: "🍌", name: "Banana", keywords: ["banana", "fruit", "yellow"] },
    { emoji: "🍇", name: "Grapes", keywords: ["grapes", "fruit", "wine"] },
    { emoji: "🍓", name: "Strawberry", keywords: ["strawberry", "fruit", "berry"] },
    { emoji: "🍑", name: "Peach", keywords: ["peach", "fruit"] },
    { emoji: "🍒", name: "Cherry", keywords: ["cherry", "fruit", "red"] },
    { emoji: "🥑", name: "Avocado", keywords: ["avocado", "guac", "green"] },
    { emoji: "🌶️", name: "Hot Pepper", keywords: ["pepper", "hot", "spicy"] },
    { emoji: "🍕", name: "Pizza", keywords: ["pizza", "food", "slice"] },
    { emoji: "🍔", name: "Burger", keywords: ["burger", "hamburger", "food"] },
    { emoji: "🍟", name: "Fries", keywords: ["fries", "chips", "food"] },
    { emoji: "🌮", name: "Taco", keywords: ["taco", "food", "mexican"] },
    { emoji: "🍩", name: "Donut", keywords: ["donut", "doughnut", "sweet"] },
    { emoji: "🍪", name: "Cookie", keywords: ["cookie", "biscuit", "sweet"] },
    { emoji: "🎂", name: "Birthday Cake", keywords: ["cake", "birthday", "celebration"] },
    { emoji: "🍰", name: "Shortcake", keywords: ["cake", "dessert", "sweet"] },
    { emoji: "🧁", name: "Cupcake", keywords: ["cupcake", "muffin", "sweet"] },
    { emoji: "☕", name: "Coffee", keywords: ["coffee", "tea", "drink", "hot"] },
    { emoji: "🍵", name: "Tea", keywords: ["tea", "green", "drink"] },
    { emoji: "🥤", name: "Cup with Straw", keywords: ["drink", "soda", "cup"] },
    { emoji: "🍺", name: "Beer", keywords: ["beer", "drink", "cheers"] },
    { emoji: "🍷", name: "Wine", keywords: ["wine", "drink", "glass"] },
    { emoji: "🥂", name: "Clinking Glasses", keywords: ["cheers", "toast", "celebrate"] },
    { emoji: "🧃", name: "Juice Box", keywords: ["juice", "drink", "box"] },
  ] },
  { key: "travel", entries: [
    { emoji: "🌍", name: "Globe Europe", keywords: ["globe", "earth", "world", "europe"] },
    { emoji: "🌎", name: "Globe Americas", keywords: ["globe", "earth", "world", "america"] },
    { emoji: "🌏", name: "Globe Asia", keywords: ["globe", "earth", "world", "asia"] },
    { emoji: "🗺️", name: "World Map", keywords: ["map", "world", "travel"] },
    { emoji: "🏠", name: "House", keywords: ["house", "home", "building"] },
    { emoji: "🏢", name: "Office", keywords: ["office", "building", "work"] },
    { emoji: "🏥", name: "Hospital", keywords: ["hospital", "medical", "health"] },
    { emoji: "🏫", name: "School", keywords: ["school", "education", "learn"] },
    { emoji: "🏛️", name: "Classical Building", keywords: ["building", "classical", "museum"] },
    { emoji: "⛪", name: "Church", keywords: ["church", "religion", "building"] },
    { emoji: "🗼", name: "Tokyo Tower", keywords: ["tower", "tokyo", "japan"] },
    { emoji: "🗽", name: "Statue of Liberty", keywords: ["liberty", "statue", "nyc"] },
    { emoji: "✈️", name: "Airplane", keywords: ["airplane", "plane", "fly", "travel"] },
    { emoji: "🚗", name: "Car", keywords: ["car", "auto", "drive"] },
    { emoji: "🚕", name: "Taxi", keywords: ["taxi", "cab", "ride"] },
    { emoji: "🚌", name: "Bus", keywords: ["bus", "transit", "ride"] },
    { emoji: "🚂", name: "Train", keywords: ["train", "rail", "locomotive"] },
    { emoji: "🚀", name: "Rocket", keywords: ["rocket", "space", "launch"] },
    { emoji: "🛸", name: "UFO", keywords: ["ufo", "alien", "flying saucer"] },
    { emoji: "⛵", name: "Sailboat", keywords: ["sailboat", "boat", "sea"] },
    { emoji: "🏖️", name: "Beach", keywords: ["beach", "vacation", "sand"] },
    { emoji: "🏔️", name: "Mountain", keywords: ["mountain", "snow", "peak"] },
    { emoji: "🌋", name: "Volcano", keywords: ["volcano", "eruption", "lava"] },
    { emoji: "🏕️", name: "Camping", keywords: ["camping", "tent", "outdoor"] },
    { emoji: "🎡", name: "Ferris Wheel", keywords: ["ferris", "wheel", "amusement"] },
    { emoji: "🌅", name: "Sunrise", keywords: ["sunrise", "morning", "dawn"] },
    { emoji: "🌄", name: "Sunrise Over Mountains", keywords: ["sunrise", "mountain", "morning"] },
    { emoji: "🌃", name: "Night City", keywords: ["night", "city", "stars"] },
    { emoji: "🌙", name: "Crescent Moon", keywords: ["moon", "night", "crescent"] },
    { emoji: "☀️", name: "Sun", keywords: ["sun", "sunny", "bright", "day"] },
    { emoji: "⛅", name: "Partly Cloudy", keywords: ["cloud", "sun", "weather"] },
    { emoji: "🌊", name: "Wave", keywords: ["wave", "ocean", "sea", "water"] },
    { emoji: "❄️", name: "Snowflake", keywords: ["snow", "cold", "winter", "ice"] },
  ] },
  { key: "flags", entries: [
    { emoji: "🇺🇸", name: "US", keywords: ["us", "usa", "america", "united states"] },
    { emoji: "🇬🇧", name: "UK", keywords: ["uk", "britain", "united kingdom", "england"] },
    { emoji: "🇩🇪", name: "Germany", keywords: ["germany", "deutsch"] },
    { emoji: "🇫🇷", name: "France", keywords: ["france", "french"] },
    { emoji: "🇪🇸", name: "Spain", keywords: ["spain", "spanish"] },
    { emoji: "🇮🇹", name: "Italy", keywords: ["italy", "italian"] },
    { emoji: "🇯🇵", name: "Japan", keywords: ["japan", "japanese"] },
    { emoji: "🇰🇷", name: "South Korea", keywords: ["korea", "korean"] },
    { emoji: "🇨🇳", name: "China", keywords: ["china", "chinese"] },
    { emoji: "🇧🇷", name: "Brazil", keywords: ["brazil", "brazilian"] },
    { emoji: "🇮🇳", name: "India", keywords: ["india", "indian"] },
    { emoji: "🇷🇺", name: "Russia", keywords: ["russia", "russian"] },
    { emoji: "🇨🇦", name: "Canada", keywords: ["canada", "canadian"] },
    { emoji: "🇦🇺", name: "Australia", keywords: ["australia", "australian"] },
    { emoji: "🇲🇽", name: "Mexico", keywords: ["mexico", "mexican"] },
    { emoji: "🇳🇱", name: "Netherlands", keywords: ["netherlands", "dutch", "holland"] },
    { emoji: "🇸🇪", name: "Sweden", keywords: ["sweden", "swedish"] },
    { emoji: "🇳🇴", name: "Norway", keywords: ["norway", "norwegian"] },
    { emoji: "🇩🇰", name: "Denmark", keywords: ["denmark", "danish"] },
    { emoji: "🇫🇮", name: "Finland", keywords: ["finland", "finnish"] },
    { emoji: "🇵🇱", name: "Poland", keywords: ["poland", "polish"] },
    { emoji: "🇵🇹", name: "Portugal", keywords: ["portugal", "portuguese"] },
    { emoji: "🇹🇷", name: "Turkey", keywords: ["turkey", "turkish"] },
    { emoji: "🇸🇦", name: "Saudi Arabia", keywords: ["saudi", "arabia"] },
    { emoji: "🇦🇪", name: "UAE", keywords: ["uae", "dubai", "emirates"] },
    { emoji: "🇹🇭", name: "Thailand", keywords: ["thailand", "thai"] },
    { emoji: "🇻🇳", name: "Vietnam", keywords: ["vietnam", "vietnamese"] },
    { emoji: "🇮🇩", name: "Indonesia", keywords: ["indonesia", "indonesian"] },
    { emoji: "🇵🇭", name: "Philippines", keywords: ["philippines", "filipino"] },
    { emoji: "🇳🇬", name: "Nigeria", keywords: ["nigeria", "nigerian"] },
    { emoji: "🇿🇦", name: "South Africa", keywords: ["south africa"] },
    { emoji: "🇦🇷", name: "Argentina", keywords: ["argentina"] },
    { emoji: "🇨🇱", name: "Chile", keywords: ["chile", "chilean"] },
    { emoji: "🇨🇴", name: "Colombia", keywords: ["colombia", "colombian"] },
    { emoji: "🏴", name: "Black Flag", keywords: ["flag", "black"] },
    { emoji: "🏳️", name: "White Flag", keywords: ["flag", "white", "surrender"] },
    { emoji: "🏁", name: "Checkered Flag", keywords: ["flag", "finish", "race"] },
    { emoji: "🚩", name: "Red Flag", keywords: ["flag", "red", "warning"] },
    { emoji: "🏳️‍🌈", name: "Rainbow Flag", keywords: ["rainbow", "pride", "lgbtq"] },
  ] },
];

export function allEmoji(): EmojiEntry[] {
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.entries) {
      if (seen.has(entry.emoji)) continue;
      seen.add(entry.emoji);
      out.push(entry);
    }
  }
  return out;
}

export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return allEmoji();
  return allEmoji().filter(
    (e) => e.name.toLowerCase().includes(q) || e.keywords.some((k) => k.includes(q)),
  );
}
