/* Portions derived from appscreen (https://github.com/YUZU-Hub/appscreen), MIT License, Copyright YuzuHub */
// The curated Google Fonts catalog (app.js:602-943). appscreen's webfonts-API fetch is dead code
// (its API key setting never existed, app.js:716), so this embedded list IS the catalog – which
// also keeps the editor deterministic offline.

export interface SystemFont {
  name: string;
  value: string;
}

export const SYSTEM_FONTS: SystemFont[] = [
  { name: "SF Pro Display", value: "-apple-system, BlinkMacSystemFont, 'SF Pro Display'" },
  { name: "SF Pro Rounded", value: "'SF Pro Rounded', -apple-system" },
  { name: "Helvetica Neue", value: "'Helvetica Neue', Helvetica" },
  { name: "Avenir Next", value: "'Avenir Next', Avenir" },
  { name: "Georgia", value: "Georgia, serif" },
  { name: "Arial", value: "Arial, sans-serif" },
  { name: "Times New Roman", value: "'Times New Roman', serif" },
  { name: "Courier New", value: "'Courier New', monospace" },
  { name: "Verdana", value: "Verdana, sans-serif" },
  { name: "Trebuchet MS", value: "'Trebuchet MS', sans-serif" },
];

export const POPULAR_FONTS: string[] = [
  "Inter", "Poppins", "Roboto", "Open Sans", "Montserrat", "Lato", "Raleway", "Nunito", "Playfair Display",
  "Oswald", "Merriweather", "Source Sans Pro", "PT Sans", "Ubuntu", "Rubik", "Work Sans", "Quicksand",
  "Mulish", "Barlow", "DM Sans", "Manrope", "Space Grotesk", "Plus Jakarta Sans", "Outfit", "Sora",
  "Lexend", "Figtree", "Albert Sans", "Urbanist", "Satoshi", "General Sans", "Bebas Neue", "Anton",
  "Archivo", "Bitter", "Cabin", "Crimson Text", "Dancing Script", "Fira Sans", "Heebo", "IBM Plex Sans",
  "Josefin Sans", "Karla", "Libre Franklin", "Lora", "Noto Sans", "Nunito Sans", "Pacifico",
  "Permanent Marker", "Roboto Condensed", "Roboto Mono", "Roboto Slab", "Shadows Into Light", "Signika",
  "Slabo 27px", "Source Code Pro", "Titillium Web", "Varela Round", "Zilla Slab", "Arimo",
  "Barlow Condensed", "Catamaran", "Comfortaa", "Cormorant Garamond", "Dosis", "EB Garamond", "Exo 2",
  "Fira Code", "Hind", "Inconsolata", "Indie Flower", "Jost", "Kanit", "Libre Baskerville", "Maven Pro",
  "Mukta", "Nanum Gothic", "Noticia Text", "Oxygen", "Philosopher", "Play", "Prompt", "Rajdhani",
  "Red Hat Display", "Righteous", "Saira", "Sen", "Spectral", "Teko", "Vollkorn", "Yanone Kaffeesatz",
  "Zeyada", "Amatic SC", "Archivo Black", "Asap", "Assistant", "Bangers", "BioRhyme", "Cairo", "Cardo",
  "Chivo", "Concert One", "Cormorant", "Cousine", "DM Serif Display", "DM Serif Text", "Dela Gothic One",
  "El Messiri", "Encode Sans", "Eczar", "Fahkwang", "Gelasio",
];

const EXTRA_FONTS: string[] = [
  "ABeeZee", "Abel", "Abhaya Libre", "Abril Fatface", "Aclonica", "Acme", "Actor", "Adamina", "Advent Pro",
  "Aguafina Script", "Akronim", "Aladin", "Aldrich", "Alef", "Alegreya", "Alegreya Sans",
  "Alegreya Sans SC", "Alex Brush", "Alfa Slab One", "Alice", "Alike", "Alike Angular", "Allan", "Allerta",
  "Allison", "Allura", "Almendra", "Amaranth", "Amatic SC", "Amethysta", "Amiko", "Amiri", "Amita",
  "Anaheim", "Andada", "Andika", "Angkor", "Annie Use Your Telescope", "Anonymous Pro", "Antic",
  "Antic Didone", "Antonio", "Arapey", "Arbutus", "Arbutus Slab", "Architects Daughter", "Archivo Narrow",
  "Aref Ruqaa", "Arima Madurai", "Arvo", "Asap Condensed", "Asar", "Asset", "Astloch", "Asul", "Athiti",
  "Atkinson Hyperlegible", "Atomic Age", "Aubrey", "Audiowide", "Autour One", "Average", "Average Sans",
  "Averia Gruesa Libre", "Averia Libre", "Averia Sans Libre", "Averia Serif Libre", "B612", "B612 Mono",
  "Bad Script", "Bahiana", "Bahianita", "Bai Jamjuree", "Baloo", "Baloo 2", "Balsamiq Sans", "Balthazar",
  "Baskervville", "Battambang", "Baumans", "Bellefair", "Belleza", "Bellota", "Bellota Text", "BenchNine",
  "Bentham", "Berkshire Swash", "Beth Ellen", "Bevan", "Big Shoulders Display", "Big Shoulders Text",
  "Bigelow Rules", "Bigshot One", "Bilbo", "Bilbo Swash Caps", "Blinker", "Bodoni Moda", "Bokor", "Bonbon",
  "Boogaloo", "Bowlby One", "Bowlby One SC", "Brawler", "Bree Serif", "Brygada 1918", "Bubblegum Sans",
  "Bubbler One", "Buda", "Buenard", "Bungee", "Bungee Hairline", "Bungee Inline", "Bungee Outline",
  "Bungee Shade", "Butcherman", "Butterfly Kids", "Cabin Condensed", "Cabin Sketch", "Caesar Dressing",
  "Cagliostro", "Caladea", "Calistoga", "Calligraffitti", "Cambay", "Cambo", "Candal", "Cantarell",
  "Cantata One", "Cantora One", "Capriola", "Cardo", "Carme", "Carrois Gothic", "Carrois Gothic SC",
  "Carter One", "Castoro", "Caveat", "Caveat Brush", "Cedarville Cursive", "Ceviche One", "Chakra Petch",
  "Changa", "Changa One", "Chango", "Charm", "Charmonman", "Chathura", "Chau Philomene One", "Chela One",
  "Chelsea Market", "Chenla", "Cherry Cream Soda", "Cherry Swash", "Chewy", "Chicle", "Chilanka",
  "Chonburi", "Cinzel", "Cinzel Decorative", "Clicker Script", "Coda", "Coda Caption", "Codystar", "Coiny",
  "Combo", "Comforter", "Comforter Brush", "Comic Neue", "Coming Soon", "Commissioner", "Condiment",
  "Content", "Contrail One", "Convergence", "Cookie", "Copse", "Corben", "Corinthia", "Cormorant Infant",
  "Cormorant SC", "Cormorant Unicase", "Cormorant Upright", "Courgette", "Courier Prime",
  "Covered By Your Grace", "Crafty Girls", "Creepster", "Crete Round", "Crimson Pro", "Croissant One",
  "Crushed", "Cuprum", "Cute Font", "Cutive", "Cutive Mono", "Damion", "Dangrek", "Darker Grotesque",
  "David Libre", "Dawning of a New Day", "Days One", "Dekko", "Delius", "Delius Swash Caps",
  "Delius Unicase", "Della Respira", "Denk One", "Devonshire", "Dhurjati", "Didact Gothic", "Diplomata",
  "Diplomata SC", "Do Hyeon", "Dokdo", "Domine", "Donegal One", "Dongle", "Doppio One", "Dorsa",
  "Droid Sans", "Droid Sans Mono", "Droid Serif", "Duru Sans", "Dynalight", "Eagle Lake", "East Sea Dokdo",
  "Eater", "Economica", "Eczar", "Edu NSW ACT Foundation", "Edu QLD Beginner", "Edu SA Beginner",
  "Edu TAS Beginner", "Edu VIC WA NT Beginner", "Electrolize", "Elsie", "Elsie Swash Caps", "Emblema One",
  "Emilys Candy", "Encode Sans Condensed", "Encode Sans Expanded", "Encode Sans Semi Condensed",
  "Encode Sans Semi Expanded", "Engagement", "Englebert", "Enriqueta", "Ephesis", "Epilogue", "Erica One",
  "Esteban", "Estonia", "Euphoria Script", "Ewert", "Exo", "Expletus Sans", "Explora", "Fahkwang",
  "Fanwood Text", "Farro", "Farsan", "Fascinate", "Fascinate Inline", "Faster One", "Fasthand",
  "Fauna One", "Faustina", "Federant", "Federo", "Felipa", "Fenix", "Festive", "Finger Paint",
  "Fira Sans Condensed", "Fira Sans Extra Condensed", "Fjalla One", "Fjord One", "Flamenco", "Flavors",
  "Fleur De Leah", "Flow Block", "Flow Circular", "Flow Rounded", "Fondamento", "Fontdiner Swanky",
  "Forum", "Francois One", "Frank Ruhl Libre", "Fraunces", "Freckle Face", "Fredericka the Great",
  "Fredoka", "Fredoka One", "Freehand", "Fresca", "Frijole", "Fruktur", "Fugaz One", "Fuggles",
  "Fuzzy Bubbles", "GFS Didot", "GFS Neohellenic", "Gabriela", "Gaegu", "Gafata", "Galada", "Galdeano",
  "Galindo", "Gamja Flower", "Gayathri", "Gelasio", "Gemunu Libre", "Genos", "Gentium Basic",
  "Gentium Book Basic", "Gentium Book Plus", "Gentium Plus", "Geo", "Georama", "Geostar", "Geostar Fill",
  "Germania One", "Gideon Roman", "Gidugu", "Gilda Display", "Girassol", "Give You Glory", "Glass Antiqua",
  "Glegoo", "Gloria Hallelujah", "Glory", "Gluten", "Goblin One", "Gochi Hand", "Goldman", "Gorditas",
  "Gothic A1", "Gotu", "Goudy Bookletter 1911", "Gowun Batang", "Gowun Dodum", "Graduate", "Grand Hotel",
  "Grandstander", "Grape Nuts", "Gravitas One", "Great Vibes", "Grechen Fuemen", "Grenze",
  "Grenze Gotisch", "Grey Qo", "Griffy", "Gruppo", "Gudea", "Gugi", "Gupter", "Gurajada", "Gwendolyn",
  "Habibi", "Hachi Maru Pop", "Hahmlet", "Halant", "Hammersmith One", "Hanalei", "Hanalei Fill", "Handlee",
  "Hanuman", "Happy Monkey", "Harmattan", "Headland One", "Hepta Slab", "Herr Von Muellerhoff",
  "Hi Melody", "Hina Mincho", "Hind Guntur", "Hind Madurai", "Hind Siliguri", "Hind Vadodara",
  "Holtwood One SC", "Homemade Apple", "Homenaje", "Hubballi", "Hurricane", "IBM Plex Mono",
  "IBM Plex Sans Condensed", "IBM Plex Serif", "IM Fell DW Pica", "IM Fell DW Pica SC",
  "IM Fell Double Pica", "IM Fell Double Pica SC", "IM Fell English", "IM Fell English SC",
  "IM Fell French Canon", "IM Fell French Canon SC", "IM Fell Great Primer", "IM Fell Great Primer SC",
  "Ibarra Real Nova", "Iceberg", "Iceland", "Imbue", "Imperial Script", "Imprima", "Inconsolata", "Inder",
  "Ingrid Darling", "Inika", "Inknut Antiqua", "Inria Sans", "Inria Serif", "Inspiration", "Inter Tight",
  "Irish Grover", "Island Moments", "Istok Web", "Italiana", "Italianno", "Itim", "Jacques Francois",
  "Jacques Francois Shadow", "Jaldi", "JetBrains Mono", "Jim Nightshade", "Joan", "Jockey One",
  "Jolly Lodger", "Jomhuria", "Jomolhari", "Josefin Slab", "Joti One", "Jua", "Judson", "Julee",
  "Julius Sans One", "Junge", "Jura", "Just Another Hand", "Just Me Again Down Here", "K2D", "Kadwa",
  "Kaisei Decol", "Kaisei HarunoUmi", "Kaisei Opti", "Kaisei Tokumin", "Kalam", "Kameron", "Kanit",
  "Kantumruy", "Kantumruy Pro", "Karantina", "Karla", "Karma", "Katibeh", "Kaushan Script", "Kavivanar",
  "Kavoon", "Kdam Thmor Pro", "Keania One", "Kelly Slab", "Kenia", "Khand", "Khmer", "Khula", "Kings",
  "Kirang Haerang", "Kite One", "Kiwi Maru", "Klee One", "Knewave", "KoHo", "Kodchasan", "Koh Santepheap",
  "Kolker Brush", "Kosugi", "Kosugi Maru", "Kotta One", "Koulen", "Kranky", "Kreon", "Kristi", "Krona One",
  "Krub", "Kufam", "Kulim Park", "Kumar One", "Kumar One Outline", "Kumbh Sans", "Kurale",
  "La Belle Aurore", "Lacquer", "Laila", "Lakki Reddy", "Lalezar", "Lancelot", "Langar", "Lateef",
  "League Gothic", "League Script", "League Spartan", "Leckerli One", "Ledger", "Lekton", "Lemon",
  "Lemonada", "Lexend Deca", "Lexend Exa", "Lexend Giga", "Lexend Mega", "Lexend Peta", "Lexend Tera",
  "Lexend Zetta", "Libre Barcode 128", "Libre Barcode 128 Text", "Libre Barcode 39",
  "Libre Barcode 39 Extended", "Libre Barcode 39 Extended Text", "Libre Barcode 39 Text",
  "Libre Barcode EAN13 Text", "Libre Bodoni", "Libre Caslon Display", "Libre Caslon Text", "Life Savers",
  "Lilita One", "Lily Script One", "Limelight", "Linden Hill", "Literata", "Liu Jian Mao Cao", "Livvic",
  "Lobster", "Lobster Two", "Londrina Outline", "Londrina Shadow", "Londrina Sketch", "Londrina Solid",
  "Long Cang", "Lora", "Love Light", "Love Ya Like A Sister", "Loved by the King", "Lovers Quarrel",
  "Luckiest Guy", "Lusitana", "Lustria", "Luxurious Roman", "Luxurious Script", "M PLUS 1",
  "M PLUS 1 Code", "M PLUS 1p", "M PLUS 2", "M PLUS Code Latin", "M PLUS Rounded 1c", "Ma Shan Zheng",
  "Macondo", "Macondo Swash Caps", "Mada", "Magra", "Maiden Orange", "Maitree", "Major Mono Display",
  "Mako", "Mali", "Mallanna", "Mandali", "Manjari", "Mansalva", "Manuale", "Marcellus", "Marcellus SC",
  "Marck Script", "Margarine", "Markazi Text", "Marko One", "Marmelad", "Martel", "Martel Sans", "Marvel",
  "Mate", "Mate SC", "Material Icons", "Material Icons Outlined", "Material Icons Round",
  "Material Icons Sharp", "Material Icons Two Tone", "Material Symbols Outlined",
  "Material Symbols Rounded", "Material Symbols Sharp", "Maven Pro", "McLaren", "Mea Culpa", "Meddon",
  "MedievalSharp", "Medula One", "Meera Inimai", "Megrim", "Meie Script", "Meow Script", "Merienda",
  "Merienda One", "Merriweather Sans", "Metal", "Metal Mania", "Metamorphous", "Metrophobic", "Michroma",
  "Milonga", "Miltonian", "Miltonian Tattoo", "Mina", "Miniver", "Miriam Libre", "Mirza", "Miss Fajardose",
  "Mitr", "Mochiy Pop One", "Mochiy Pop P One", "Modak", "Modern Antiqua", "Mogra", "Mohave", "Molengo",
  "Molle", "Monda", "Monofett", "Monoton", "Monsieur La Doulaise", "Montaga", "Montagu Slab", "MonteCarlo",
  "Montez", "Montserrat Alternates", "Montserrat Subrayada", "Moo Lah Lah", "Moon Dance", "Moul",
  "Moulpali", "Mountains of Christmas", "Mouse Memoirs", "Mr Bedfort", "Mr Dafoe", "Mr De Haviland",
  "Mrs Saint Delafield", "Mrs Sheppards", "Ms Madi", "Mukta Mahee", "Mukta Malar", "Mukta Vaani", "Muli",
  "Murecho", "MuseoModerno", "My Soul", "Mystery Quest", "NTR", "Nanum Brush Script",
  "Nanum Gothic Coding", "Nanum Myeongjo", "Nanum Pen Script", "Neonderthaw", "Nerko One", "Neucha",
  "Neuton", "New Rocker", "New Tegomin", "News Cycle", "Newsreader", "Niconne", "Niramit", "Nixie One",
  "Nobile", "Nokora", "Norican", "Nosifer", "Notable", "Nothing You Could Do", "Noticia Text",
  "Noto Color Emoji", "Noto Emoji", "Noto Kufi Arabic", "Noto Music", "Noto Naskh Arabic",
  "Noto Nastaliq Urdu", "Noto Rashi Hebrew", "Noto Sans Arabic", "Noto Sans Bengali",
  "Noto Sans Devanagari", "Noto Sans Display", "Noto Sans Georgian", "Noto Sans Hebrew", "Noto Sans HK",
  "Noto Sans JP", "Noto Sans KR", "Noto Sans Mono", "Noto Sans SC", "Noto Sans TC", "Noto Sans Thai",
  "Noto Serif", "Noto Serif Bengali", "Noto Serif Devanagari", "Noto Serif Display", "Noto Serif Georgian",
  "Noto Serif Hebrew", "Noto Serif JP", "Noto Serif KR", "Noto Serif SC", "Noto Serif TC",
  "Noto Serif Thai", "Nova Cut", "Nova Flat", "Nova Mono", "Nova Oval", "Nova Round", "Nova Script",
  "Nova Slim", "Nova Square", "Numans", "Nunito", "Nunito Sans", "Nuosu SIL", "Odibee Sans",
  "Odor Mean Chey", "Offside", "Oi", "Old Standard TT", "Oldenburg", "Ole", "Oleo Script",
  "Oleo Script Swash Caps", "Oooh Baby", "Open Sans Condensed", "Oranienbaum", "Orbit", "Orbitron",
  "Oregano", "Orelega One", "Orienta", "Original Surfer", "Oswald", "Otomanopee One", "Outfit",
  "Over the Rainbow", "Overlock", "Overlock SC", "Overpass", "Overpass Mono", "Ovo", "Oxanium",
  "Oxygen Mono", "PT Mono", "PT Sans Caption", "PT Sans Narrow", "PT Serif", "PT Serif Caption",
  "Pacifico", "Padauk", "Padyakke Expanded One", "Palanquin", "Palanquin Dark", "Palette Mosaic",
  "Pangolin", "Paprika", "Parisienne", "Passero One", "Passion One", "Passions Conflict",
  "Pathway Gothic One", "Patrick Hand", "Patrick Hand SC", "Pattaya", "Patua One", "Pavanam",
  "Paytone One", "Peddana", "Peralta", "Permanent Marker", "Petemoss", "Petit Formal Script", "Petrona",
  "Phetsarath", "Philosopher", "Piazzolla", "Piedra", "Pinyon Script", "Pirata One", "Plaster", "Play",
  "Playball", "Playfair Display SC", "Podkova", "Poiret One", "Poller One", "Poly", "Pompiere",
  "Pontano Sans", "Poor Story", "Poppins", "Port Lligat Sans", "Port Lligat Slab", "Potta One",
  "Pragati Narrow", "Praise", "Prata", "Preahvihear", "Press Start 2P", "Pridi", "Princess Sofia",
  "Prociono", "Prompt", "Prosto One", "Proza Libre", "Public Sans", "Puppies Play", "Puritan",
  "Purple Purse", "Qahiri", "Quando", "Quantico", "Quattrocento", "Quattrocento Sans", "Questrial",
  "Quicksand", "Quintessential", "Qwigley", "Qwitcher Grypen", "Racing Sans One", "Radio Canada", "Radley",
  "Rajdhani", "Rakkas", "Raleway Dots", "Ramabhadra", "Ramaraja", "Rambla", "Rammetto One", "Rampart One",
  "Ranchers", "Rancho", "Ranga", "Rasa", "Rationale", "Ravi Prakash", "Readex Pro", "Recursive",
  "Red Hat Mono", "Red Hat Text", "Red Rose", "Redacted", "Redacted Script", "Redressed", "Reem Kufi",
  "Reenie Beanie", "Reggae One", "Revalia", "Rhodium Libre", "Ribeye", "Ribeye Marrow", "Righteous",
  "Risque", "Road Rage", "Roboto Flex", "Rochester", "Rock Salt", "RocknRoll One", "Rokkitt", "Romanesco",
  "Ropa Sans", "Rosario", "Rosarivo", "Rouge Script", "Rowdies", "Rozha One", "Rubik Beastly",
  "Rubik Bubbles", "Rubik Burned", "Rubik Dirt", "Rubik Distressed", "Rubik Glitch", "Rubik Marker Hatch",
  "Rubik Maze", "Rubik Microbe", "Rubik Mono One", "Rubik Moonrocks", "Rubik Puddles", "Rubik Wet Paint",
  "Ruda", "Rufina", "Ruge Boogie", "Ruluko", "Rum Raisin", "Ruslan Display", "Russo One", "Ruthie", "Rye",
  "STIX Two Math", "STIX Two Text", "Sacramento", "Sahitya", "Sail", "Saira Condensed",
  "Saira Extra Condensed", "Saira Semi Condensed", "Saira Stencil One", "Salsa", "Sanchez", "Sancreek",
  "Sansita", "Sansita Swashed", "Sarabun", "Sarala", "Sarina", "Sarpanch", "Sassy Frass", "Satisfy",
  "Sawarabi Gothic", "Sawarabi Mincho", "Scada", "Scheherazade New", "Schoolbell", "Scope One",
  "Seaweed Script", "Secular One", "Sedgwick Ave", "Sedgwick Ave Display", "Sen", "Send Flowers",
  "Sevillana", "Seymour One", "Shadows Into Light Two", "Shalimar", "Shanti", "Share", "Share Tech",
  "Share Tech Mono", "Shippori Antique", "Shippori Antique B1", "Shippori Mincho", "Shippori Mincho B1",
  "Shizuru", "Shojumaru", "Short Stack", "Shrikhand", "Siemreap", "Sigmar One", "Signika Negative",
  "Silkscreen", "Simonetta", "Single Day", "Sintony", "Sirin Stencil", "Six Caps", "Skranji", "Slabo 13px",
  "Slackey", "Smokum", "Smooch", "Smooch Sans", "Smythe", "Sniglet", "Snippet", "Snowburst One",
  "Sofadi One", "Sofia", "Sofia Sans", "Sofia Sans Condensed", "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed", "Solitreo", "Solway", "Song Myung", "Sophia", "Sora", "Sorts Mill Goudy",
  "Source Code Pro", "Source Sans 3", "Source Serif 4", "Source Serif Pro", "Space Mono", "Spartan",
  "Special Elite", "Spectral SC", "Spicy Rice", "Spinnaker", "Spirax", "Splash", "Spline Sans",
  "Spline Sans Mono", "Squada One", "Square Peg", "Sree Krushnadevaraya", "Sriracha", "Srisakdi",
  "Staatliches", "Stalemate", "Stalinist One", "Stardos Stencil", "Stick", "Stick No Bills",
  "Stint Ultra Condensed", "Stint Ultra Expanded", "Stoke", "Strait", "Style Script", "Stylish",
  "Sue Ellen Francisco", "Suez One", "Sulphur Point", "Sumana", "Sunflower", "Sunshiney",
  "Supermercado One", "Sura", "Suranna", "Suravaram", "Suwannaphum", "Swanky and Moo Moo", "Syncopate",
  "Syne", "Syne Mono", "Syne Tactile", "Tajawal", "Tangerine", "Tapestry", "Taprom", "Tauri", "Taviraj",
  "Teko", "Telex", "Tenali Ramakrishna", "Tenor Sans", "Text Me One", "Texturina", "Thasadith",
  "The Girl Next Door", "The Nautigal", "Tienne", "Tillana", "Tilt Neon", "Tilt Prism", "Tilt Warp",
  "Timmana", "Tinos", "Tiro Bangla", "Tiro Devanagari Hindi", "Tiro Devanagari Marathi",
  "Tiro Devanagari Sanskrit", "Tiro Gurmukhi", "Tiro Kannada", "Tiro Tamil", "Tiro Telugu", "Titan One",
  "Trade Winds", "Train One", "Trirong", "Trispace", "Trocchi", "Trochut", "Truculenta", "Trykker",
  "Tulpen One", "Turret Road", "Twinkle Star", "Ubuntu Condensed", "Ubuntu Mono", "Uchen", "Ultra",
  "Uncial Antiqua", "Underdog", "Unica One", "UnifrakturCook", "UnifrakturMaguntia", "Unkempt", "Unlock",
  "Unna", "Updock", "Urbanist", "Varta", "Vast Shadow", "Vazirmatn", "Vesper Libre", "Viaoda Libre",
  "Vibes", "Vibur", "Vidaloka", "Viga", "Voces", "Volkhov", "Vollkorn SC", "Voltaire", "Vujahday Script",
  "Waiting for the Sunrise", "Wallpoet", "Walter Turncoat", "Warnes", "Water Brush", "Waterfall",
  "Wellfleet", "Wendy One", "Whisper", "WindSong", "Wire One", "Wix Madefor Display", "Wix Madefor Text",
  "Work Sans", "Xanh Mono", "Yaldevi", "Yanone Kaffeesatz", "Yantramanav", "Yatra One", "Yellowtail",
  "Yeon Sung", "Yeseva One", "Yesteryear", "Yomogi", "Yrsa", "Ysabeau", "Ysabeau Infant", "Ysabeau Office",
  "Ysabeau SC", "Yuji Boku", "Yuji Hentaigana Akari", "Yuji Hentaigana Akebono", "Yuji Mai", "Yuji Syuku",
  "Yusei Magic", "ZCOOL KuaiLe", "ZCOOL QingKe HuangYou", "ZCOOL XiaoWei", "Zen Antique",
  "Zen Antique Soft", "Zen Dots", "Zen Kaku Gothic Antique", "Zen Kaku Gothic New", "Zen Kurenaido",
  "Zen Loop", "Zen Maru Gothic", "Zen Old Mincho", "Zen Tokyo Zoo", "Zeyada", "Zhi Mang Xing",
  "Zilla Slab Highlight",
];

export const ALL_FONTS: string[] = [...new Set([...POPULAR_FONTS, ...EXTRA_FONTS])].sort();
